AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Exclude:
    - 'lib/**/version.rb'

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false